language: csharp
solution: alugamer.sln

mono: none
dotnet: 3.1
script:
 - dotnet restore
 - msbuild /p:Configuration=Release alugamer.sln
 - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./Alugamer.Testes/bin/Release/Alugamer.Testes.dll