language: csharp
solution: Alugamer.sln
dotnet: 3.1
mono: none

addons:
  browserstack:
    username: "voull1"
    access_key: $BROWSERSTACK_KEY

script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test