language: csharp
solution: Alugamer.sln
dotnet: 3.1
mono: none

addons:
  browserstack:
    username: "voull1"
    access_key:
      secure: "vEBNbPJ3zICMmBfyp07FEcz22FdvbdneOHjEFnnnJC0aQ7drOvQugOQofnES5qZ7o3C0EC4FcoZ8MAFrCJV68RxJFOV5m4q1ZJ9WBH5pmRpvFNrXw4O9Zrak4Po6nRgU/w+I7kMgLK0XvBMkDUbW0nyyn5uBGMwPmfgO//cs7yd4tlFWCoNqgFxOzrbTm2KUKw/KEvZspkxBCDUWOczg5u38DbN/NLoepTX0n+TH/7K4zATpe5YRlqDJ7h5eUhaj1/mZs0OSiPjmigwFkMhSzjdNtBkocKWnCLM96cyUw90z9/wkt3gssyQqu6L2yyy8rJG/pA+L+MEyxu6Vuf21nvyLr2qO3zcpW7FApxQfrejTlIiVu4FKMqbaLoJoSZRU8jg+rw5dTiQ/Bep2iIFg9reqDMDHwKjNQN90s1SkKZ5G/gNvUsNqkxWgGLnw6uZozZf9ZbE71wsiT7veLQCyGst4zBTZNmpJ7iBHJ7D72qr4QSxGLw3OXuI8vGh2nTguDgxU/A9DhHfEsjlGIcp1vpajNrufbAda6SK6cqtcWE//t/cz27kBIghGeBzwdzz7sXYO5f06Vxjx7NIKpiVWJ5AnFZksIUcOD8KJZaNsA6Ou1Wy+5n8B9SlIuTJdjffcYqNwTyUB1a+9zaKhfe8l8xVqifiKIs0GUZxx9t8yp0E="
    forcelocal: true

script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test -c "TRAVIS"