DELETE FROM CAD_CLIENTES
DELETE FROM CAD_ALUGAVEIS
DELETE FROM CAD_MODULOS

DELETE FROM PERFIS_MODULOS

DELETE FROM CAD_LOGIN

DELETE FROM CAD_PERFIS
DELETE FROM CAD_FUNCIONARIOS

INSERT INTO CAD_CLIENTES (NOME, EMAIL, TELEFONE, ENDERECO, DATA_NASCIMENTO, SEXO, CPF) VALUES ('Joaquim', 'joaquim@gmail.com', '(11)1111-1111', 'Rua da Macieira, 44', '1997-01-05', 'M', '111.111.111-11')
INSERT INTO CAD_ALUGAVEIS (NOME, DESCRICAO, QUANTIDADE, VALOR_COMPRA, VALOR_ALUGUEL, CATEGORIA) VALUES ('Nintendo Switch - Red/Blue Joycons', 'Console Nintendo Switch Edição Joycons Vermelho/Azul', 1, 1500, 85, 'Console')
INSERT INTO CAD_FUNCIONARIOS (NOME, EMAIL, TELEFONE, ENDERECO, DATA_NASCIMENTO, SEXO, CPF) VALUES ('Marcos', 'marcos@gmail.com', '(15)1111-1111', 'Rua da Laranjeira, 17', '1987-01-05', 'M', '222.222.222-22')